# MIT License
#
# (C) Copyright [2022] Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

# Dockerfile for building Cray-HPE hmnfd (HMI Notification Fanout Daemon)
# for CT testing.

# Base image contains everything needed for Go building, just build.
FROM artifactory.algol60.net/docker.io/library/golang:1.16-alpine AS builder

RUN set -ex \
    && apk -U upgrade \
    && apk add build-base

RUN go env -w GO111MODULE=auto

# Copy all the necessary files to the image.
COPY cmd $GOPATH/src/github.com/Cray-HPE/hms-hmi-nfd/cmd
COPY vendor $GOPATH/src/github.com/Cray-HPE/hms-hmi-nfd/vendor

# Base image contains everything needed for Go building, just build.

RUN set -ex && go build -v -tags musl -i -o /usr/local/bin/hmnfd github.com/Cray-HPE/hms-hmi-nfd/cmd/hmi-nfd

### Final Stage ###

FROM artifactory.algol60.net/docker.io/alpine:3.15
LABEL maintainer="Hewlett Packard Enterprise"
STOPSIGNAL SIGTERM

# Copy the final binary.  

COPY --from=builder /usr/local/bin/hmnfd /usr/local/bin

# Run the daemon

ENV DEBUG=0
ENV SM_URL=http://cray-smd:27779/hsm/v2
ENV INBOUND_SCN_URL="https://cray-hmnfd:28600/hmi/v1/scn"
ENV SM_RETRIES=3
ENV SM_TIMEOUT=10
ENV PORT=28600
ENV ETCD_HOST=etcd
ENV ETCD_PORT=2379
ENV TELEMETRY_HOST=kafka:9092:cray-hmsstatechange-notifications

# Force fanout sync mode to insure there is no indeterminate ordering of 
# SCN reception

ENV HMNFD_FANOUT_SYNC=1

# Use this for in-memory datastore (no good for API testing)
#ENV KV_URL="mem:"

# Use this for the docker-compose usage of ETCD.  NOTE: not sure why
# this isn't 'etcd-server' rather than 'etcd'??

ENV KV_URL="http://etcd:2379"
#ENV KV_URL="http://etcd-server:2379"

# nobody 65534:65534
USER 65534:65534

CMD ["sh", "-c", "hmnfd --debug=$DEBUG $NOSM --sm_url=$SM_URL --sm_retries=$SM_RETRIES --sm_timeout=$SM_TIMEOUT -port=$PORT --kv_url=$KV_URL --scn_in_url=$INBOUND_SCN_URL $USE_TELEMETRY --telemetry_host=$TELEMETRY_HOST"]
