# Copyright 2019-2020 Hewlett Packard Enterprise Development LP
# MIT License
#
# (C) Copyright [2021] Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

# Dockerfile for building HMS fake node/SCN subscriber for testing.
# Author: mpkelly
# Date: 12-February 2019

FROM dtr.dev.cray.com/baseos/golang:1.14-alpine3.12 AS builder

COPY Test/fake-subscriber/fake-subscriber.go ${GOPATH}/src/fake-subscriber/

RUN set -ex && go build -v -i -o /usr/local/bin/fake-subscriber fake-subscriber

### Final Stage ###

FROM dtr.dev.cray.com/baseos/alpine:3.12
LABEL maintainer="Cray, Inc."
STOPSIGNAL SIGTERM

# Copy the final binary.  

COPY --from=builder /usr/local/bin/fake-subscriber /usr/local/bin

# Run the fake-subscriber daemon.  Env vars come from the .yaml file.

CMD ["sh", "-c", "fake-subscriber"]
